working golang image

diff --git a/Golang/s2i/bin/assemble b/Golang/s2i/bin/assemble
--- a/Golang/s2i/bin/assemble
+++ b/Golang/s2i/bin/assemble
@@ -1,38 +1,73 @@
-#!/bin/bash -e
-#
-# S2I assemble script for the 'golang-builder' image.
-# The 'assemble' script builds your application source so that it is ready to run.
-#
-# For more information refer to the documentation:
-#	https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
-#
+#!/bin/bash
 
-set -o errexit
+set -e
 
-# If the 'golang-builder' assemble script is executed with the '-h' flag, print the usage.
-if [[ "$1" == "-h" ]]; then
-	exec /usr/libexec/s2i/usage
+pushd /tmp/src
+
+if [[ `go list -f {{.Incomplete}}` == "true" || ! -z "$IMPORT_URL" ]]; then
+
+    INSTALL_URL=${INSTALL_URL:-$IMPORT_URL}
+
+    if [[ ! -z "$IMPORT_URL" ]]; then
+
+        popd
+
+        echo "Assembling GOPATH"
+
+        export GOPATH=`realpath $HOME/go`
+
+        mkdir -p $GOPATH/src/$IMPORT_URL
+
+        mv /tmp/src/* $GOPATH/src/$IMPORT_URL
+
+        if [[ -d /tmp/artifacts/pkg || -d /tmp/artifacts/go-build ]]; then
+
+            echo "Restoring previous build artifacts"
+
+            mv /tmp/artifacts/pkg $GOPATH
+            GOCACHE=`go env GOCACHE`
+            mkdir -p $GOCACHE
+            mv /tmp/artifacts/go-build $GOCACHE
+
+        fi
+
+        # Resolve dependencies, ignore if vendor present
+
+        if [[ ! -d $GOPATH/src/$INSTALL_URL/vendor && `go list -f {{.Incomplete}} $INSTALL_URL` == "true" ]]; then
+
+            echo "Resolving dependencies"
+
+            pushd $GOPATH/src/$INSTALL_URL
+
+            go get
+
+            popd
+
+        fi
+
+        # lets build
+
+        pushd $GOPATH/src/$INSTALL_URL
+
+        echo "Building"
+
+        go install $INSTALL_URL
+
+        mv $GOPATH/bin/* /opt/app-root/gobinary
+
+        popd
+
+        exit
+
+    fi
+
+    echo "ERROR: Package is missing dependencies and IMPORT_URL inference failed. Set IMPORT_URL env var."
+    exec /$STI_SCRIPTS_PATH/usage
+
+else
+
+    go build -o /opt/app-root/gobinary
+
+    popd
+
 fi
-
-# Restore artifacts from the previous build (if they exist).
-#
-if [ "$(ls /tmp/artifacts/ 2>/dev/null)" ]; then
-  echo "---> Restoring build artifacts..."
-  mv /tmp/artifacts/. ./
-fi
-
-echo "---> Installing application source..."
-cp -Rf /tmp/src/. ./
-
-echo "---> Downloading dependencies..."
-go get -v
-
-# The -o app is important, as we have set this in the 
-# s2i/bin/run script, allowing it to run whatever app was
-# generated by the build below
-echo "---> Building application from source..."
-go build -v -o app -a -installsuffix cgo
-
-echo "---> Running tests..."
-go test -v -o app_test.go
-
